  container: {
    flex: 1,
    backgroundColor: "#F0F0F0",
    justifyContent: "space-between",
  },
  content: {
    marginTop: 40,
  },
  header: {
    backgroundColor: "#1C3048",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    height: 60,
  },
  menuIcon: {
    position: "absolute",
    left: 10,
    top: 12,
    width: 32,
    height: 32,
    tintColor: "black",
  },
  headerText: {
    color: "#FFFFFF",
    fontSize: 23,
    fontWeight: "bold",
    textShadowColor: "#000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 5,
    marginLeft: 55,
    paddingBottom: 6,
  },
  connectButton: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "#1C3048",
    justifyContent: "center",
    alignItems: "center",
    margin: 100,
    borderColor: "#73B5E5",
    borderWidth: 6,
  },
  connectButtonPressed: {
    backgroundColor: "black",
  },
  connectText: {
    color: "#FFFFFF",
    fontSize: 21,
    fontWeight: "bold",
    textAlign: "center",
  },
  connectTextPressed: {
    color: "blue",
    fontWeight: "bold",
  },
  bluetooth_connectivity: {
    width: 50,
    height: 50,
    marginLeft: 155,
    marginTop: -40,
  },
  footer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  footerText: {
    color: "#1C3048",
    fontSize: 15,
    fontWeight: "bold",
  },